import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

import { ThemeProvider } from "./_components/theme";
import ReownProvider from "@/lib/web3/provider";
import { cookies as nextCookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await nextCookies();
  const cookies = cookieStore.get("cookies")?.value ?? null;
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <ReownProvider cookies={cookies}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            forcedTheme="dark"
          >
            {children}
          </ThemeProvider>
        </ReownProvider>
      </body>
    </html>
  );
}
